product-name: control-plane
network-properties:
  network:
    name: {{.control_plane_subnet_name}}
  other_availability_zones:
    - name: 'zone-2'
  singleton_availability_zone:
    name: 'zone-1'
product-properties:
  .properties.domain:
    value: {{.control_plane_domain}}
  .properties.control_plane_database:
    value: external
  .properties.control_plane_database.external.host:
    value: {{.control_plane_fqdn}}
  .properties.control_plane_database.external.port:
    value: '5432'
  .properties.control_plane_database.external.atc_db_name:
    value: atc
  .properties.control_plane_database.external.atc_db_username:
    value: {{.control_plane_db_username}}
  .properties.control_plane_database.external.atc_db_password:
    value:
      secret: {{.control_plane_db_password}}
  .properties.control_plane_database.external.credhub_db_name:
    value: credhub
  .properties.control_plane_database.external.credhub_db_username:
    value: {{.control_plane_db_username}}
  .properties.control_plane_database.external.credhub_db_password:
    value:
      secret: {{.control_plane_db_password}}
  .properties.control_plane_database.external.uaa_db_name:
    value: uaa
  .properties.control_plane_database.external.uaa_db_username:
    value: {{.control_plane_db_username}}
  .properties.control_plane_database.external.uaa_db_password:
    value:
      secret: {{.control_plane_db_password}}
  .properties.control_plane_database.external.ca_cert:
    value: {{toJson .db_ca_cert}}
resource-config:
  web:
    instances: automatic
    elb_names:
    - {{.control_plane_lb_name}}
    internet_connected: true
  worker:
    internet_connected: true
